### ISSUE TITLE
Write some tests

### ISSUE THREAD

**Issue by boybundit** [boybundit/linebot#1]
Probably using [mocha](https://mochajs.org/) and [supertest](https://github.com/visionmedia/supertest)

**Comment by andela-celisha-wigwe** [comment]
Hi @boybundit I'm interested in giving this a try. I just set up a new account and channel on LINE.
However I'm trying to get the access token. Do you mind helping out? I need the info to be able to try out the application, before working on the issues.

**Comment by boybundit** [comment]
Hi @andela-celisha-wigwe I followed the instruction [here](https://developers.line.me/messaging-api/getting-started) to get the access token for the chat bot using LINE@ account option as it is free to start. Then in the [LINE@](https://play.google.com/store/apps/details?id=com.linecorp.lineat.android) app, we can add chat bot as friend to test out.

**Comment by boybundit** [comment]
Fixed by #2
