### ISSUE TITLE
Push message to multiple users

### ISSUE THREAD

**Issue by boybundit** [boybundit/linebot#12]
In `LineBot.push(to, message)`, if `to` is an array of string, loop through that array to push message to multiple users.

**Comment by tmpace** [comment]
I'd like to work on this!

**Comment by boybundit** [comment]
Sure, thanks. Looking forward to your PR.

**Comment by kytwb** [comment]
@tmpace still working on it? I would like to take it otherwise.

**Comment by tmpace** [comment]
@kytwb Go ahead, apologies, I've been tied up with work!

**Comment by boybundit** [comment]
Fiexed by #14
