### ISSUE TITLE
Cannot run demo echo-express

### ISSUE THREAD

**Issue by golfapipol** [boybundit/linebot#15]
I try it before but today, it crash!

**Comment by boybundit** [comment]
@golfapipol What is the error that you got? Are you using the latest version of linebot@1.2.0?

**Comment by golfapipol** [comment]
yes, It's already linebot version 1.2.0 
<img width="281" alt="screen shot 2559-11-04 at 10 27 19" src="https://cloud.githubusercontent.com/assets/8346755/19993624/a541ac22-a279-11e6-9fed-1f6392f1da40.png">

**Comment by golfapipol** [comment]
Oh! my fault I using another token....
but I got new error when subscript
<img width="710" alt="screen shot 2559-11-04 at 11 08 24" src="https://cloud.githubusercontent.com/assets/8346755/19994296/3c3c3cb4-a27f-11e6-84dd-de56b8101e62.png">

**Comment by boybundit** [comment]
From your stack trace, it is because `event.message.text` is `undefined`, which can happen when the bot receives non-text messages e.g. sticker. Workaround is to avoid passing `undefined `or `null `into `reply` method.

The lib should be patched to implement better validation to prevent the crash.

**Comment by boybundit** [comment]
It shouldn't crash now in 1.2.1. Could you please try?
