### ISSUE TITLE
Get user agent

### ISSUE THREAD

**Issue by azzuwan** [boybundit/linebot#17]
Is there anyway I can get the user agent info to detect whether it's mobile or desktop browser?

**Comment by boybundit** [comment]
I cannot find any way to do that from [LINE API Reference](https://devdocs.line.me/en/#messaging-api). You may try checking HTTP header `req.headers['user-agent']` but I think it won't work as it is LINE server that calls the webhook, not the LINE app client.

**Comment by azzuwan** [comment]
I'm going to try and slot a normal connect middleware before the webhook url get's processed and will let you know how that works out.
