### ISSUE TITLE
About get the username

### ISSUE THREAD

**Issue by jacklee814** [boybundit/linebot#23]
in the Event.source.profile(), I cant save the username to a variable from profile.displayName?

like this ...

```
let username;
event.source.profile().then(function (profile) {
	event.reply('Hello ' + profile.displayName);
}).catch(function (error) {
	// error
});
console.log(username); // undefined
```

**Comment by boybundit** [comment]
@jacklee814 You need to do that within the callback function. For example,

```javascript
let username;
event.source.profile().then(function (profile) {
  username = profile.displayName;
  console.log(username);
});
```

**Comment by jacklee814** [comment]
Ok. thank you

**Comment by boybundit** [comment]
@jacklee814 I've seen that sometimes too, and also cannot find any answer from their documentation.  My guess is that those users haven't accepted the terms and conditions. They may use older version of LINE, or they may just chat to the bot without adding it as friend.

**Comment by jacklee814** [comment]
thanks for your reply.
