### ISSUE TITLE
Update package.json file to exclude unnecessary files

### ISSUE THREAD

**Issue by boybundit** [boybundit/linebot#4]
Like test and CI config file

**Comment by boybundit** [comment]
Let's use [package.json](https://docs.npmjs.com/files/package.json#files) instead of .npmignore

**Comment by mohitbhatia1994** [comment]
I will do it. Claimed.

**Comment by xRahul** [comment]
Hey @boybundit 

You would have to use .npmignore to exclude files, as the files property in package.json is used to include them, not exclude. We can add all the folders and files we want to include in package.json, but that would have to be updated with every new file created, which would be unnecessary work. Please check

**Comment by boybundit** [comment]
@xRahul Thanks for the suggestion. I was thinking the same, but decided to use package.json just because it does not require yet another config file.

I might change my mind later if it breaks because we forget to update package.json....

**Comment by xRahul** [comment]
@boybundit alright!
