### ISSUE TITLE
add <client>.getGroupSummary(groupId)

### ISSUE THREAD

**Issue by Uryaaa** [boybundit/linebot#60]
need new api update :<

**Comment by WayneChang65** [comment]
also need PRs review >.<...

**Comment by WayneChang65** [comment]
@Uryaaa In fact, I've already implemented it. But still waiting for the previous PR review(#56). Well, I'm considering merge new apis to my fork repo.  If I have time.... Orz

**Comment by WayneChang65** [comment]
@Uryaaa I've created a fork repo and added API functions. Check it out. [WayneChang65/linebot2](https://github.com/WayneChang65/linebot2)

**Comment by Uryaaa** [comment]
Thankyou very much !! Been using this amazing package for 6 months now 😅 then should i close this issue?

**Comment by WayneChang65** [comment]
@Uryaaa No Problem. Thanks.
